language: python
sudo: required

matrix:
  include:
    - dist: trusty
      env: dist="14.04 LTS trusty" openflow="1.3"
    - dist: trusty
      env: dist="14.04 LTS trusty" openflow="1.0"

#    - dist: xenial
#      env: dist="16.04 LTS xenial"
# Travis-CI only proposes 14.04 LTS Trusty and there is no plan to update to 16.04 xenial
# (c.f. https://github.com/travis-ci/travis-ci/issues/5821)
# It is useless to add a second job because it will run in the same Ubuntu version (14.04)

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq vlan
- sudo util/install.sh -n

install:
- bash -c "if [ `lsb_release -rs` == '14.04' ]; then make codecheck; fi"
- bash -c "if [ "$openflow" == '1.3' ] ; then sudo util/install.sh -3fnvw; echo "Openflow 1.3"; else sudo util/install.sh -fnvw; echo "Openflow 1.0" fi"

script:
- sudo mn --test pingall
- sudo python mininet/test/runner.py -v -quick
- sudo python examples/test/runner.py -v -quick

notifications:
  email:
    on_success: never
# More details: https://docs.travis-ci.com/user/notifications#Configuring-email-notifications
